esphome:
  name: ${device_id}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
  on_boot:
    - priority: 220.0
      then:
        # - it8951e.clear
        - delay: 100ms
        - component.update: epaper_display
    - priority: -100.0
      then:
        - delay: 10s
        - component.update: epaper_display

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable psram
psram:

# Enable Home Assistant API
api:

ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: TooManyComp
  password: BigBasement

globals:
  - id: material_icons_map
    type: std::map<std::string, std::string>
    restore_value: no
    initial_value: |
      {
        {"mdi-weather-night", "󰖔"},
        {"mdi-weather-cloudy", "󰖐"},
        {"mdi-weather-cloudy-alert", "󰼯"},
        {"mdi-weather-fog", "󰖑"},
        {"mdi-weather-hail", "󰖒"},
        {"mdi-weather-lightning-rainy", "󰙾"},
        {"mdi-weather-lightning", "󰖓"},
        {"mdi-weather-partly-cloudy", "󰖕"},
        {"mdi-weather-night-partly-cloudy", "󰼱"},
        {"mdi-weather-pouring", "󰖖"},
        {"mdi-weather-rainy", "󰖗"},
        {"mdi-weather-snowy-rainy", "󰙿"},
        {"mdi-weather-snowy", "󰖘"},
        {"mdi-weather-sunny", "󰖙"},
        {"mdi-weather-windy-variant", "󰖞"},
        {"mdi-weather-windy", "󰖝"},
        {"mdi-cloud-question", "󰨹"},
        {"mdi-thermometer", "󰔏"},
        {"mdi-water-percent", "󰖎"},
        {"mdi-molecule-co2", "󰟤"},
        {"mdi-wind-power-outline", "󱪉"},
        {"mdi-home-outline", "󰚡"},
        {"mdi-tree-outline", "󰹩"},
        {"mdi-gauge", "󰊚"},
        {"mdi-battery-high", "󱊣"},
        {"mdi-battery-medium", "󱊢"},
        {"mdi-battery-low", "󱊡"},
        {"mdi-battery-alert-variant-outline", "󱃍"},
        {"mdi-battery-charging-high", "󱊦"},
        {"mdi-battery-unknown", "󰂑"},
        {"mdi-shield-outline", "󰒙"},
        {"mdi-shield-home-outline", "󰳋"},
        {"mdi-shield-lock-outline", "󰳌"},
        {"mdi-shield-moon-outline", "󱠩"},
        {"mdi-shield-alert-outline", "󰻍"},
        {"mdi-molecule-co2", "󰟤"},
        {"mdi-radioactive", "󰐼"},
        {"mdi-numeric-0-circle-outline", "󰲟"},
        {"mdi-numeric-1-circle-outline", "󰲡"},
        {"mdi-numeric-2-circle-outline", "󰲣"},
        {"mdi-numeric-3-circle-outline", "󰲥"},
        {"mdi-numeric-4-circle-outline", "󰲧"},
        {"mdi-numeric-5-circle-outline", "󰲩"},
        {"mdi-numeric-6-circle-outline", "󰲫"},
        {"mdi-numeric-7-circle-outline", "󰲭"},
        {"mdi-numeric-8-circle-outline", "󰲯"},
        {"mdi-numeric-9-plus-circle-outline", "󰲳"},
      }

font:
  - file: 'gfonts://Roboto'
    id: normal_font
    size: 40
  - file: 'gfonts://Roboto@medium'
    id: condition_font
    size: 80
  - file: "gfonts://Orbitron"
    id: clock_font
    size: 80
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: small_icons_font
    size: 50
    glyphs: [
        '󰖖',    #mdi-weather-pouring
        '󰔏',    #mdi-thermometer
        '󰖎',    #mdi-water-percent
        '󰟤',    #mdi-molecule-co2
        '󱪉',    #mdi-wind-power-outline
        '󰚡',    #mdi-home-outline
        '󰹩',    #mdi-tree-outline
        '󰊚',    #mdi-gauge
      ]
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: weather_font
    size: 256
    glyphs: [
        '󰖔',    #mdi-weather-night
        '󰖐',    #mdi-weather-cloudy
        '󰼯',    #mdi-weather-cloudy-alert
        '󰖑',    #mdi-weather-fog
        '󰖒',    #mdi-weather-hail
        '󰙾',    #mdi-weather-lightning-rainy
        '󰖓',    #mdi-weather-lightning
        '󰖕',    #mdi-weather-partly-cloudy
        '󰼱',    #mdi-weather-night-partly-cloudy
        '󰖖',    #mdi-weather-pouring
        '󰖗',    #mdi-weather-rainy
        '󰙿',    #mdi-weather-snowy-rainy
        '󰖘',    #mdi-weather-snowy
        '󰖙',    #mdi-weather-sunny
        '󰖞',    #mdi-weather-windy-variant
        '󰖝',    #mdi-weather-windy
        '󰨹',    #mdi-cloud-question
      ]
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: battery_font
    size: 40
    glyphs: [
        '󱊣',    #mdi-battery-high
        '󱊢',    #mdi-battery-medium
        '󱊡',    #mdi-battery-low
        '󱃍',    #mdi-battery-alert-variant-outline
        '󱊦',    #mdi-battery-charging-high
        '󰂑',    #mdi-battery-unknown
      ]
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: alarms_font
    size: 80
    glyphs: [
        '󰒙',    #mdi-shield-outline
        '󰳋',    #mdi-shield-home-outline
        '󰳌',    #mdi-shield-lock-outline
        '󱠩',    #mdi-shield-moon-outline
        '󰻍',    #mdi-shield-alert-outline
        '󰟤',    #mdi-molecule-co2
        '󰐼',    #mdi-radioactive
        '󰲟',    #mdi-numeric-0-circle-outline
        '󰲡',    #mdi-numeric-1-circle-outline
        '󰲣',    #mdi-numeric-2-circle-outline
        '󰲥',    #mdi-numeric-3-circle-outline
        '󰲧',    #mdi-numeric-4-circle-outline
        '󰲩',    #mdi-numeric-5-circle-outline
        '󰲫',    #mdi-numeric-6-circle-outline
        '󰲭',    #mdi-numeric-7-circle-outline
        '󰲯',    #mdi-numeric-8-circle-outline
        '󰲳',    #mdi-numeric-9-plus-circle-outline
      ]

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14
  miso_pin: GPIO12

display:
  - platform: waveshare_epaper
    id: epaper_display
    cs_pin: GPIO15
    dc_pin: GPIO27
    reset_pin: GPIO26
    reset_duration: 100ms
    busy_pin: 
      number: GPIO25
      inverted: true
    model: 7.50in-bV3
    rotation: 0
    reversed: False
    update_interval: never
    lambda: |-
      // Clock
      it.strftime(25, 420, id(clock_font), "%H:%M", id(rtc_time).now());

      // Weather icon
      Color weather_icon_color;
      weather_icon_color.raw_32 = 0x0D;
      #if 0 // Use for testing
      std::string _conditions[] {
        "clear-night",
        "cloudy",
        "exceptional",
        "fog",
        "hail",
        "lightning-rainy",
        "lightning",
        "partlycloudy",
        "pouring",
        "rainy",
        "snowy-rainy",
        "snowy",
        "sunny",
        "windy",
        "windy-variant",
      };
      static int _cond_index = 0;
      std::string conditions = _conditions[_cond_index];
      _cond_index = (_cond_index + 1) % 15;
      #else
      std::string conditions = id(weather_conditions).state;
      #endif
      std::string img = id(material_icons_map)["mdi-cloud-question"];
      if (conditions == "clear-night")
      {
          conditions = "clear";
          img = id(material_icons_map)["mdi-weather-night"];
      }
      else if (conditions == "cloudy")
          img = id(material_icons_map)["mdi-weather-cloudy"];
      else if (conditions == "exceptional")
          img = id(material_icons_map)["mdi-weather-cloudy-alert"];
      else if (conditions == "fog")
          img = id(material_icons_map)["mdi-weather-fog"];
      else if (conditions == "hail")
          img = id(material_icons_map)["mdi-weather-hail"];
      else if (conditions == "lightning-rainy")
      {
          conditions = "thunderstorm";
          img = id(material_icons_map)["mdi-weather-lightning-rainy"];
      }
      else if (conditions == "lightning")
          img = id(material_icons_map)["mdi-weather-lightning"];
      else if (conditions == "partlycloudy")
      {
          bool is_night = id(sun_position).state == "below_horizon";
          if (is_night)
              img = id(material_icons_map)["mdi-weather-night-partly-cloudy"];
          else
              img = id(material_icons_map)["mdi-weather-partly-cloudy"];
          conditions = "partly cloudy";
      }
      else if (conditions == "pouring")
      {
          img = id(material_icons_map)["mdi-weather-pouring"];
          conditions = "shower";
      }
      else if (conditions == "rainy")
          img = id(material_icons_map)["mdi-weather-rainy"];
      else if (conditions == "snowy-rainy")
      {
          img = id(material_icons_map)["mdi-weather-snowy-rainy"];
          conditions = "sleet";
      }
      else if (conditions == "snowy")
          img = id(material_icons_map)["mdi-weather-snowy"];
      else if (conditions == "sunny")
          img = id(material_icons_map)["mdi-weather-sunny"];
      else if (conditions == "windy")
          img = id(material_icons_map)["mdi-weather-windy"];
      else if (conditions == "windy-variant")
      {
          img = id(material_icons_map)["mdi-weather-windy-variant"];
          conditions = "windy";
      }
      it.print(25, 55, id(weather_font), weather_icon_color, img.c_str());

      uint base_y = -50;

      #define NOT_NAN(x) ((x) == (x))

      // Outdoor
      it.print(295, base_y + 100, id(small_icons_font), weather_icon_color, id(material_icons_map)["mdi-tree-outline"].c_str());
      it.print(355, base_y + 100, id(normal_font), "Outdoor:");
      // Temperature
      it.print(295, base_y + 150, id(small_icons_font), weather_icon_color, id(material_icons_map)["mdi-thermometer"].c_str());
      float temp = id(outdoor_temperature).state;
      if (NOT_NAN(temp))
        it.printf(355, base_y + 150, id(normal_font), "%.1f°C", temp);
      else
        it.print(355, base_y + 150, id(normal_font), "---");
      // Humidity
      it.print(295, base_y + 200, id(small_icons_font), weather_icon_color, id(material_icons_map)["mdi-water-percent"].c_str());
      float humidity = id(outdoor_humidity).state;
      if (NOT_NAN(humidity))
        it.printf(355, base_y + 200, id(normal_font), "%.1f%%", humidity);
      else
        it.print(355, base_y + 200, id(normal_font), "---");
      // Rainfall
      it.print(295, base_y + 250, id(small_icons_font), weather_icon_color, id(material_icons_map)["mdi-weather-pouring"].c_str());
      float rainfall = id(outdoor_rainfall).state;
      if (NOT_NAN(rainfall))
        it.printf(355, base_y + 250, id(normal_font), "%.1f mm", rainfall);
      else
        it.print(355, base_y + 250, id(normal_font), "---");
      // Wind strength
      it.print(295, base_y + 300, id(small_icons_font), weather_icon_color, id(material_icons_map)["mdi-wind-power-outline"].c_str());
      float wind_strength = id(outdoor_wind_strength).state;
      if (NOT_NAN(wind_strength))
        it.printf(355, base_y + 300, id(normal_font), "%d km/h", (int)wind_strength);
      else
        it.print(355, base_y + 300, id(normal_font), "---");

      float solar_power = id(solar_energy).state;
      if (NOT_NAN(solar_power))
        it.printf(355, base_y + 350, id(normal_font), "%d w", (int)solar_power);
      else
        it.print(355, base_y + 300, id(normal_font), "---");

      // Indoor
      it.print(560, base_y + 100, id(small_icons_font), weather_icon_color, id(material_icons_map)["mdi-home-outline"].c_str());
      it.print(620, base_y + 100, id(normal_font), "Indoor:");
      // Temperature
      it.print(560, base_y + 150, id(small_icons_font), weather_icon_color, id(material_icons_map)["mdi-thermometer"].c_str());
      temp = id(indoor_temperature).state;
      if (NOT_NAN(temp))
        it.printf(620, base_y + 150, id(normal_font), "%.1f°C", temp);
      else
        it.print(620, base_y + 150, id(normal_font), "---");
      // Humidity
      it.print(560, base_y + 200, id(small_icons_font), weather_icon_color, id(material_icons_map)["mdi-water-percent"].c_str());
      humidity = id(indoor_humidity).state;
      if (NOT_NAN(humidity))
        it.printf(620, base_y + 200, id(normal_font), "%.1f%%", humidity);
      else
        it.print(620, base_y + 200, id(normal_font), "---");

graph:
  - id: energy_graph
    sensor: solar_energy
    duration: 12h
    min_value: 0
    max_value: 10000
    width: 600
    height: 120
    x_grid: 5min
    y_grid: 500
    border: true

switch:
  - platform: restart
    id: restart_switch
    name: ${device_name} Restart

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Australia/Canberra
    on_time_sync:
      - bm8563.write_time
  - platform: bm8563
    id: rtc_time
    sleep_duration: 60000ms
    on_time:
      - seconds: 0
        then:
          - component.update: epaper_display


sensor:
  - platform: homeassistant
    name: Soler Energy
    id: solar_energy
    entity_id: sensor.total_dc_power
  - platform: homeassistant
    name: Outdoor temperature
    id: outdoor_temperature
    entity_id: ${outdoor_temperature}
  - platform: homeassistant
    name: Outdoor humidity
    id: outdoor_humidity
    entity_id: ${outdoor_humidity}
  - platform: homeassistant
    name: Rainfall last hour
    id: outdoor_rainfall
    entity_id: ${outdoor_rainfall}
  - platform: homeassistant
    name: Wind strength
    id: outdoor_wind_strength
    entity_id: ${outdoor_wind_strength}
  - platform: homeassistant
    name: Indoor temperature
    id: indoor_temperature
    entity_id: ${indoor_temperature}
  - platform: homeassistant
    name: Indoor humidity
    id: indoor_humidity
    entity_id: ${indoor_humidity}

text_sensor:
  - platform: homeassistant
    name: Weather
    id: weather_conditions
    entity_id: ${weather_conditions}
  - platform: homeassistant
    name: Sun
    id: sun_position
    entity_id: sun.sun
