esphome:
  name: accontroller
  friendly_name: Aircon Controller
  includes:
    - <sstream>

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LWIP_MAX_SOCKETS: "16"
    advanced:
      enable_lwip_tcpip_core_locking: true 

external_components:
  - source: components
#    components: [ http_request ]

# Enable logging
logger:
  level: INFO
  baud_rate: 0
  logs:
    component: ERROR
    sensor: INFO
    switch: INFO
    climate: INFO
    http_request.idf: INFO
    homeassistant.sensor: INFO
    main: INFO

# syslog:
#   port: 514
#   strip: true

# Enable Home Assistant API
api:
  encryption:
    key: "b6ymMt4mQmDtPxisG5/EXZzWRwzYgXN+7S7GC/UK6nc="

ota:
  - platform: esphome
    password: "b910852b7a32d2b59c0cb21ab2bb1d2b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

mdns:
  disabled: false

web_server:
  include_internal: True
  js_include: "./v2/www.js"
  js_url: ""
  css_url: ""
  css_include: "./v2/webserver-v1.min.js"
  version: 2
  log: true

udp:
  addresses: 192.168.12.20
  port:
    listen_port: 8666
    broadcast_port: 18511

  on_receive: 
    then:
      - logger.log: 
          format: "%s Rebooting..."
          args: [ 'std::string(data.begin(), data.end()).c_str()' ]
          level: WARN
      - if:
          condition:
            lambda: 'return std::string(data.begin(), data.end()).starts_with("RESTART");'
          then:
            - delay: 2s
            - button.press: reboot_now

debug:

number:
  - platform: template
    name: Master Offset
    optimistic: True
    min_value: -5
    max_value: 5
    step: 1
    initial_value: -2
    restore_value: true
  - platform: template
    id: heat_offset
    name: Heat Offset
    optimistic: True
    min_value: 0
    max_value: 10
    step: 1
    initial_value: 4
    restore_value: true
  - platform: template
    name: Cool Offset
    id: cool_offset
    optimistic: True
    min_value: -10
    max_value: 0
    step: 1
    initial_value: -4
    restore_value: true

switch:
  - platform: gpio
    id: Zone1
    pin: GPIO32
    name: Zone Jude Study
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: Zone2
    pin: GPIO33
    name: Zone Double Bedroom
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: Zone3
    pin: GPIO25
    name:  Zone Single Bedroom
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: Zone4
    pin: GPIO26
    name:  Zone Master Bedroom
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: gpio
    id: ledlink
    pin: GPIO23

sensor:
  - platform: homeassistant
    id: house_temp
    entity_id: sensor.house_temp
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"

climate:
  - platform: thermostat
    id: ac
    name: "AC"
    sensor: house_temp
    min_cooling_off_time: 10s
    min_cooling_run_time: 10s
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    cool_deadband: 0.2
    cool_overrun: 0.5
    heat_deadband: 0.2
    heat_overrun: 0.5
    fan_with_cooling: true
    fan_with_heating: true
    min_fan_mode_switching_time: 1s
    min_fanning_off_time: 1s
    min_fanning_run_time: 1s
    # temperature_step: 0.1
    min_idle_time: 30s
    cool_action:
      - logger.log: 
          level: INFO
          format: Cooling Start
      - script.execute: mode_changed
    heat_action:
      - logger.log: 
          level: INFO
          format: Heating Start
      - script.execute: mode_changed
    idle_action:
      - logger.log: 
          level: INFO
          format: Idle Start
      - script.execute: mode_changed
    off_mode:
      - logger.log: 
          level: INFO
          format: Turned Off
      - script.execute: turn_on
    heat_mode:
      - logger.log: 
          level: INFO
          format: Set to Heat
      - script.execute: turn_on
    cool_mode:
      - logger.log: 
          level: INFO
          format: Set to Cool
      - script.execute: turn_on
    heat_cool_mode:
      - logger.log: 
          level: INFO
          format: Set to Heat/Cool
      - script.execute: turn_on
    fan_only_action:
      - logger.log: 
          level: INFO
          format: Fan Only
      - script.execute: mode_changed
    fan_mode_auto_action:
      - logger.log: 
          level: INFO
          format: Fan Auto
      - script.execute: mode_changed
    fan_mode_low_action:
      - logger.log: 
          level: INFO
          format: Fan Low
      - script.execute: mode_changed
    fan_mode_medium_action:
      - logger.log: 
          level: INFO
          format: Fan Medium
      - script.execute: mode_changed
    fan_mode_high_action:
      - logger.log: 
          level: INFO
          format: Fan High
      - script.execute: mode_changed
    preset_change:
      - logger.log: 
          level: INFO
          format: Preset changed
      - script.execute: mode_changed
    target_temperature_change_action:
      - logger.log: 
          level: INFO
          format: Target Temp changed
      - script.execute: mode_changed

    default_preset: Summer Day
    preset:
      - name: Summer Day
        default_target_temperature_low: 20 °C
        default_target_temperature_high: 23 °C
        mode: COOL
      - name: Summer Night
        default_target_temperature_low: 20 °C
        default_target_temperature_high: 22.5 °C
        mode: COOL
      - name: Winter Day
        default_target_temperature_low: 19.6 °C
        default_target_temperature_high: 21 °C
        mode: HEAT
      - name: Winter Night
        default_target_temperature_low: 17 °C
        default_target_temperature_high: 21 °C
        mode: HEAT

globals:
  - id: turned_on
    type: int
    restore_value: yes
  - id: url
    type: std::string
    restore_value: no
    initial_value: '"http://192.168.12.35/skyfi/aircon/"'

time:
  - platform: homeassistant
    id: homeassistant_time

http_request:
  timeout: 10s
  verify_ssl: false

button:
  - platform: restart
    id: reboot_now
    name: "Ac Controller Restart"
    on_press: 
      then:
        - logger.log: 
            level: WARN
            format: Rebooting...

mapping:
  - id: daikin
    from: string
    to: int
    entries:
      ac_mode: 99

script:
  - id: turn_on
    mode: single
    then:
      - logger.log: 
          level: DEBUG
          format: Turn on Script
      - lambda: id(turned_on) = id(homeassistant_time).now().timestamp;
      - script.execute: mode_changed
      - script.execute: check_daikin_info

  - id: mode_changed
    mode: restart
    then:
      - logger.log: 
          level: DEBUG
          format: Controls changed
      - lambda: |-
          if (id(ac).mode == CLIMATE_MODE_HEAT) {
            id(daikin).set("ac_mode", 1);
            id(daikin).set("ac_pow", 1);
            id(daikin).set("ac_temp", id(ac).target_temperature_low);
            id(daikin).set("ac_offset", id(heat_offset).state);
          }
          else
          if (id(ac).mode == CLIMATE_MODE_COOL) {
            id(daikin).set("ac_mode", 2);
            id(daikin).set("ac_pow", 1);
            id(daikin).set("ac_temp", id(ac).target_temperature_high);
            id(daikin).set("ac_offset", id(cool_offset).state);
          }
          else
          if (id(ac).mode == CLIMATE_MODE_HEAT_COOL) {
            id(daikin).set("ac_mode", 0);
            id(daikin).set("ac_pow", 1);
            if (id(ac).action == CLIMATE_ACTION_HEATING) {
                id(daikin).set("ac_temp", id(ac).target_temperature_low);
                id(daikin).set("ac_offset", id(heat_offset).state);
            }
            else
            if (id(ac).action == CLIMATE_ACTION_COOLING) {
                id(daikin).set("ac_temp", id(ac).target_temperature_high);
                id(daikin).set("ac_offset", id(cool_offset).state);
            }
            else {
                id(daikin).set("ac_temp", id(ac).target_temperature_high - id(cool_offset).state);
                id(daikin).set("ac_offset", 0);
            }
          }
          else
          if (id(ac).mode == CLIMATE_MODE_OFF) {
            id(daikin).set("ac_pow", 0);
            id(daikin).set("ac_mode", 0);
          }
          if (id(ac).action == CLIMATE_ACTION_IDLE || id(ac).action == CLIMATE_ACTION_OFF) {
            id(daikin).set("ac_idle", -2);
          }
          else
            id(daikin).set("ac_idle", 1);

          if (id(ac).fan_mode == CLIMATE_FAN_LOW)
              id(daikin).set("ac_fan", 1);
          else if (id(ac).fan_mode == CLIMATE_FAN_MEDIUM)
              id(daikin).set("ac_fan", 3);
          else if (id(ac).fan_mode == CLIMATE_FAN_HIGH)
              id(daikin).set("ac_fan", 5);
          else
              id(daikin).set("ac_fan", 0);


  - id: check_daikin_info
    mode: queued
    max_runs: 2
    then:
      - logger.log: 
          format: Check Daikin Info
          level: INFO
      - lambda: |-
          if (id(daikin)["ac_mode"] == 99)
            id(mode_changed)->execute();

      - http_request.get:
          url: !lambda 'return id(url) + "get_control_info";'
          capture_response: true
          on_response:
            then:
              - lambda: |-
                  std::stringstream ss(body);
                  std::string segment;

                  //ESP_LOGD("custom", body.c_str());
                  while (std::getline(ss, segment, ',')) {
                      size_t equals_pos = segment.find('=');
                      if (equals_pos != std::string::npos) {
                          std::string key = segment.substr(0, equals_pos);
                          int value = atoi(segment.substr(equals_pos + 1).c_str());
                          id(daikin).set(key, value);
                      }
                  }
          on_error:
            - logger.log: 
                level: WARN
                format: "http error"
            - script.stop: check_daikin_info
      - if:
          condition:
            lambda: |-
              if (id(daikin)["pow"] == 0 && id(ac).mode != CLIMATE_MODE_OFF && id(turned_on) != -1) {
                int seconds_elapsed = id(homeassistant_time).now().timestamp - id(turned_on);
                return seconds_elapsed > 120;
              }
              else
                return 0;

          then:
            - logger.log: Daikin turned off
            - climate.control:
                id: ac
                mode: "OFF"
            
      - if:
          condition:
            lambda: |-
              if (id(ac).mode == CLIMATE_MODE_FAN_ONLY)
                return false;

              if (id(daikin)["ac_pow"] == 0)
                return id(daikin)["ac_pow"] == id(daikin)["pow"];

              int temp = id(daikin)["ac_temp"] + (id(daikin)["ac_idle"] * id(daikin)["ac_offset"]);
              //ESP_LOGD("custom", "Daikin Temp(%d) %d,%d", temp, id(daikin)["ac_idle"], id(daikin)["ac_offset"]);
              return (
                        id(daikin)["ac_pow"] == id(daikin)["pow"]
                        &&
                        id(daikin)["ac_mode"] == id(daikin)["mode"] 
                        && 
                        id(daikin)["stemp"] == temp 
                        && 
                        id(daikin)["f_rate"] == id(daikin)["ac_fan"]
                     );

          then:
            - if:
                condition:
                  lambda: 'return id(daikin)["ac_pow"] == 1;'
                then:
                  - logger.log:
                      format: "Daikin in sync %d, %d"
                      args: ['id(daikin)["ac_temp"] + (id(daikin)["ac_idle"] * id(daikin)["ac_offset"])', 'id(daikin)["ac_mode"]']
                      level: DEBUG
          else:
            - logger.log:
                format: "Update Daikin %d, %d, %d"
                args: ['id(daikin)["ac_temp"] + (id(daikin)["ac_idle"] * id(daikin)["ac_offset"])', 'id(daikin)["ac_mode"]', 'id(daikin)["ac_pow"]']
                level: INFO
            - http_request.get:
                url: !lambda |-
                  char buf[256];
                  int temp = round(id(daikin)["ac_temp"] + (id(daikin)["ac_idle"] * id(daikin)["ac_offset"]));
                  
                  sprintf(buf, "%sset_control_info?mode=%d&f_airside=0&dt2=%d&bk_auto=2&f_rate=%d&shum=0&pow=%d&stemp=%d&f_dir=0&f_auto=0", id(url).c_str(), id(daikin)["ac_mode"], temp, id(daikin)["ac_fan"], id(daikin)["ac_pow"], temp);

                  return std::string(buf);
                
                capture_response: false
                on_error:
                  - logger.log: 
                      level: WARN
                      format: "http error"

interval:
  - interval: 30s
    startup_delay: 10s
    then:
      - script.execute: check_daikin_info