substitutions:
  delay_time: 3min
  retry_time: 30s
  interval_time: 7min

esphome:
  name: garagebmw
  friendly_name: BMW Garage
  on_boot:
    then:
      - cover.close: door
      - globals.set: 
          id: auto_close_enabled
          value: 'true'

esp8266:
  board: esp8285

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "CJRgX+EyE3T54id7npiIQkyLujgnzj6gPZSlsKmMG2U="

ota:
  password: "7b5a2ae627be3ada2cce531da9014daf"
  platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

globals:
  - id: auto_close_enabled
    type: bool
    restore_value: yes
    initial_value: 'true'
        
switch:
  - platform: gpio
    id: relay
    pin: 
      number: 13
      inverted: false
    on_turn_on:
    - delay: 250ms
    - switch.turn_off: relay

  - platform: template
    name: "Auto Close"
    id: auto_mode
    optimistic: true
    lambda: |-
      if (id(auto_close_enabled)) {
        return true;
      } else {
        return false;
      }
    on_turn_on: 
      then:
        - globals.set: 
            id: auto_close_enabled
            value: 'true'
    on_turn_off: 
      then:
        - globals.set: 
            id: auto_close_enabled
            value: 'false'
  
binary_sensor:
  - platform: gpio
    id: button
    pin: 
      number: GPIO0
      inverted: true
    on_press:
      - script.stop: auto_close
      - if:
          condition:
            binary_sensor.is_on: sensor  # open
          then:
            if:
              condition:
                - lambda: "return id(auto_close_enabled) == true;"
              then:
                - logger.log: "Set Auto Close Off"
                - switch.template.publish:
                    id: auto_mode
                    state: OFF
              else:
                - cover.close: door
          else:
            - cover.open: door
            - switch.template.publish:
                id: auto_mode
                state: OFF
 
  - platform: gpio
    pin: 
      number: GPIO12
      inverted: false
    internal: true
    id: sensor
    on_press:
      - script.execute: auto_close
    on_release:
      - globals.set: 
          id: auto_close_enabled
          value: 'true'
#      - switch.template.publish:
#          id: auto_mode
#          state: ON


script:
  - id: auto_close
    mode: restart
    then:
      - if:
          condition:
            - lambda: "return id(auto_close_enabled) == true;"
          then:
            - logger.log: "Door Open, waiting to close"
            - delay: $delay_time
            - logger.log: "Auto Close Close Door"
            - cover.close: door
          else:
            - logger.log: "Auto Close is Off"

cover:
  - platform: template
    device_class: garage
    id: door
    name: Door
    lambda: |-
      if (id(sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      if:
        condition:
          binary_sensor.is_off: sensor
        then:
          switch.turn_on: relay
    close_action:
      if:
        condition:
          binary_sensor.is_on: sensor
        then:
          switch.turn_on: relay
    stop_action:
      switch.turn_on: relay

web_server:
  include_internal: true
  js_include: "./v2/www.js"
  js_url: ""
  css_url: ""
  css_include: "./v2/webserver-v1.min.js"
  version: 2
