substitutions:
  delay_time: 3min
  retry_time: 30s
  interval_time: 7min

esphome:
  name: garagebmw
  friendly_name: garage_bmw
  on_boot:
    then:
      - cover.close: door

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CJRgX+EyE3T54id7npiIQkyLujgnzj6gPZSlsKmMG2U="

ota:
  password: "7b5a2ae627be3ada2cce531da9014daf"
  platform: esphome
  
wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

globals:
  - id: auto_close_enabled
    type: bool
    restore_value: yes
    initial_value: 'true'
        
switch:
  - platform: gpio
    id: relay
    pin: 
      number: 13
      inverted: false
    on_turn_on:
    - delay: 250ms
    - switch.turn_off: relay

  - platform: template
    name: "Auto Close"
    restore_mode: ALWAYS_ON
    lambda: |-
      if (id(auto_close_enabled)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - globals.set: 
          id: auto_close_enabled
          value: 'true'
    turn_off_action:
      - globals.set: 
          id: auto_close_enabled
          value: 'false'

binary_sensor:
  - platform: gpio
    id: button
    pin: 
      number: GPIO0
      inverted: true
    on_press:
      - script.stop: auto_close
      - if:
          condition:
            binary_sensor.is_on: sensor
          then:
            - logger.log: "Set Auto Close On and Close"
            - globals.set: 
                id: auto_close_enabled
                value: 'true'
          else:
            - logger.log: "Set Auto Close Off and Open"
            - globals.set: 
                id: auto_close_enabled
                value: 'false'
      - switch.turn_on: relay

  - platform: gpio
    pin: 
      number: GPIO12
      inverted: true
    internal: true
    id: sensor
    on_press:
      - script.execute: auto_close

script:
  - id: auto_close
    then:
      - if:
          condition:
            - lambda: "return id(auto_close_enabled) == true;"
          then:
            - logger.log: "Door Open, waiting to close"
            - delay: $delay_time
            - logger.log: "Auto Close Close Door"
            - cover.close: door
            - globals.set: 
                id: auto_close_enabled
                value: 'true'
          else:
            - logger.log: "Auto Close is Off"

cover:
  - platform: template
    device_class: garage
    id: door
    name: Door
    lambda: |-
      if (id(sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      if:
        condition:
          binary_sensor.is_off: sensor
        then:
          switch.turn_on: relay
    close_action:
      if:
        condition:
          binary_sensor.is_on: sensor
        then:
          switch.turn_on: relay
    stop_action:
      switch.turn_on: relay


mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  discovery: false

web_server:
  port: 80
  include_internal: true
