substitutions:
  device_name: Kitchen Panel
  device_id: kitchen-panel
  # Home assistant sensors
  # Weather conditions
  weather_conditions: weather.forecast_bromellws
  # Outdoor sensors
  outdoor_humidity: sensor.bromellws_sensors_humidity
  outdoor_rainfall: sensor.bromellws_sensors_precipitation_today
  outdoor_wind_strength: sensor.bromellws_sensors_wind_speed
  # Indoor sensors
  indoor_temperature: sensor.kitchen_temp
  indoor_humidity: sensor.kitchen_panel_humidity
 
esphome:
  name: ${device_id}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
  on_boot:
    - priority: -100.0
      then:
        - delay: 10s
        - component.update: epaper_display
  includes:
    - <sstream>
    - text_wrap.h

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

external_components:
  - source: github://Passific/m5paper_esphome

# Enable logging
logger:
#  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "WGDr9wLYiaHS2gge3zWiKTAj2kK+XjlCTI6d1vYHhf0="

ota:
  password: "e9f90e328a558a632d9b598e9ea5afe4"
  platform: esphome

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: material_icons_map
    type: std::map<std::string, std::string>
    restore_value: no
    initial_value: |
      {
        {"mdi:weather-night", "󰖔"},
        {"mdi:weather-cloudy", "󰖐"},
        {"mdi:weather-cloudy-alert", "󰼯"},
        {"mdi:weather-fog", "󰖑"},
        {"mdi:weather-hail", "󰖒"},
        {"mdi:weather-lightning-rainy", "󰙾"},
        {"mdi:weather-lightning", "󰖓"},
        {"mdi:weather-partly-cloudy", "󰖕"},
        {"mdi:weather-night-partly-cloudy", "󰼱"},
        {"mdi:weather-pouring", "󰖖"},
        {"mdi:weather-rainy", "󰖗"},
        {"mdi:weather-snowy-rainy", "󰙿"},
        {"mdi:weather-snowy", "󰖘"},
        {"mdi:weather-sunny", "󰖙"},
        {"mdi:weather-windy-variant", "󰖞"},
        {"mdi:weather-windy", "󰖝"},
        {"mdi-thermometer", "󰔏"},
        {"mdi-water-percent", "󰖎"},
        {"mdi-molecule-co2", "󰟤"},
        {"mdi-wind-power-outline", "󱪉"},
        {"mdi-home-outline", "󰚡"},
        {"mdi-tree-outline", "󰹩"},
        {"mdi-gauge", "󰊚"},
        {"mdi-battery-high", "󱊣"},
        {"mdi-battery-medium", "󱊢"},
        {"mdi-battery-low", "󱊡"},
        {"mdi-battery-alert-variant-outline", "󱃍"},
        {"mdi-battery-charging-high", "󱊦"},
        {"mdi-battery-unknown", "󰂑"},
        {"mdi-shield-outline", "󰒙"},
        {"mdi-shield-home-outline", "󰳋"},
        {"mdi-shield-lock-outline", "󰳌"},
        {"mdi-shield-moon-outline", "󱠩"},
        {"mdi-shield-alert-outline", "󰻍"},
        {"mdi-molecule-co2", "󰟤"},
        {"mdi-radioactive", "󰐼"},
        {"mdi-numeric-0-circle-outline", "󰲟"},
        {"mdi-numeric-1-circle-outline", "󰲡"},
        {"mdi-numeric-2-circle-outline", "󰲣"},
        {"mdi-numeric-3-circle-outline", "󰲥"},
        {"mdi-numeric-4-circle-outline", "󰲧"},
        {"mdi-numeric-5-circle-outline", "󰲩"},
        {"mdi-numeric-6-circle-outline", "󰲫"},
        {"mdi-numeric-7-circle-outline", "󰲭"},
        {"mdi-numeric-8-circle-outline", "󰲯"},
        {"mdi-numeric-9-plus-circle-outline", "󰲳"},
        {"mdi-solar-panel-large", "󰶜"},
        {"home-lightning-bolt-outline", "󱤄"},
      }

font:
  - file: 'gfonts://Roboto'
    id: normal_font
    size: 52
  - file: 'gfonts://Roboto'
    id: small_font
    size: 36
  - file: 'gfonts://Roboto'
    id: tiny_font
    size: 24
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: small_icons_font
    size: 50
    glyphs: [
        '󰊚',    # mdi-gauge
        '󰶜',    # mdi-solar-panel-large
        '󱤄',    # mdi-home-lightning-bolt-outline
        '󰴾',    # mdi-transmission-tower
        "\U000F1901", # mdi:home-battery
        "\U000F12A5",     # mdi:battery-charging-medium
        "\U000F1019"    # care-coolant-level
      ]
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: weather_font
    size: 196
    glyphs: [
        '󰖔',    #mdi-weather-night
        '󰖐',    #mdi-weather-cloudy
        '󰼯',    #mdi-weather-cloudy-alert
        '󰖑',    #mdi-weather-fog
        '󰖒',    #mdi-weather-hail
        '󰙾',    #mdi-weather-lightning-rainy
        '󰖓',    #mdi-weather-lightning
        '󰖕',    #mdi-weather-partly-cloudy
        '󰼱',    #mdi-weather-night-partly-cloudy
        '󰖖',    #mdi-weather-pouring
        '󰖗',    #mdi-weather-rainy
        '󰙿',    #mdi-weather-snowy-rainy
        '󰖘',    #mdi-weather-snowy
        '󰖙',    #mdi-weather-sunny
        '󰖞',    #mdi-weather-windy-variant
        '󰖝',    #mdi-weather-windy
      ]

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14
  miso_pin: GPIO12

display:
  - platform: waveshare_epaper
    id: epaper_display
    cs_pin: GPIO15
    dc_pin: GPIO27
    reset_pin: GPIO26
    reset_duration: 100ms
    busy_pin: 
      number: GPIO25
      inverted: true
    model: 7.50in-bV3
    rotation: 0
    update_interval: never
    lambda: |-
      // Clock
      // it.strftime(25, 420, id(clock_font), "%H:%M", id(rtc_time).now());

      // Weather icon
      Color weather_icon_color;
      weather_icon_color.raw_32 = 0x0D;

      std::string conditions = id(weather_icon).state;

      std::string img = id(material_icons_map)[conditions.c_str()];

      uint left = 24;
      it.print(16, 8, id(weather_font), weather_icon_color, img.c_str());

      float value;


      #define NOT_NAN(x) ((x) == (x))

      // value = id(outdoor_temperature).state;
      // if (NOT_NAN(value))
      //   it.printf(left, 200, id(small_font), "%.1f°C (M %.1f)", value, id(max_temp).state);
      // else
      //   it.print(left, 200, id(small_font), "---");

      // value = id(kitchen_temp).state;
      // if (NOT_NAN(value))
      //   it.printf(left, 245, id(small_font), "Inside %.1f°C", value);
      // else
      //   it.print(left, 245, id(small_font), "---");

      // value = id(rain_today).state;
      // if (NOT_NAN(value))
      //   it.printf(left, 290, id(small_font), "%.1f mm (%.1f)", value, id(max_rain).state);
      // else
      //   it.print(left, 290, id(small_font), "---");

      // value = id(rain_rate).state;
      // if (NOT_NAN(value))
      //   it.printf(left, 320, id(small_font), "%.1f mm/h", value);
      // else
      //   it.print(left, 320, id(small_font), "---");

      // value = id(tank_level).state;
      // float perc = value * 100 / 2200.0;
      // if (NOT_NAN(value))
      //   it.printf(left, 380, id(small_font), "%.0f lt (%.0f%%)", value, perc);


      uint col1 = 20;
      uint col2 = 280;
      uint col3 = 570;

      uint base_y = 220;
      uint rowgap = 90;
      uint halfgap = 25;
      uint gap = 70;

      wrap_text(&it, col2 + gap, 26, id(weather_desc).state.c_str(), id(tiny_font), TextAlign::TOP_LEFT, 1);
      //it.graph(col1, 6, id(energy_graph));

      it.printf(col1 + gap, base_y - halfgap, id(tiny_font), "Outdoor °C");
      it.printf(col2 + gap, base_y - halfgap, id(tiny_font), "Indoor °C");
      it.printf(col3 + gap, base_y - halfgap, id(tiny_font), "Rain mm");

      it.printf(col1, base_y, id(tiny_font), "%4.1f", id(max_temp).state);
      it.printf(col1, base_y + halfgap, id(tiny_font), "%4.1f", id(min_temp).state);

      value = id(outdoor_temperature).state;
      if (NOT_NAN(value))
        it.printf(col1 + gap, base_y, id(normal_font), "%.1f", value);

      value = id(house_temp).state;
      if (NOT_NAN(value))
        it.printf(col2 + gap, base_y, id(normal_font), "%.1f", value);

      it.printf(col3, base_y, id(tiny_font), "%.1f%%", id(rain_chance).state);
      it.printf(col3, base_y + halfgap, id(tiny_font), "%.0f-%.0f", id(min_rain).state, id(max_rain).state);
      value = id(rain_today).state;
      if (NOT_NAN(value))
        it.printf(col3 + gap + 10, base_y, id(normal_font), "%.1f", value);


      base_y += 60;

      value = id(humidity).state;
      if (NOT_NAN(value))
        it.printf(col1 + gap, base_y, id(small_font), "%4.0f%%", value);

      it.print(col2 - gap, base_y, id(tiny_font), "Humidity");
      value = id(kitchen_humidity).state;
      if (NOT_NAN(value))
        it.printf(col2 + gap, base_y, id(small_font), "%4.0f%%", value);

      base_y += 30;
      it.print(col3, base_y, id(small_icons_font), weather_icon_color, "\U000F1019");
      value = id(tank_level).state;
      float perc = value * 100 / 2200.0;
      if (NOT_NAN(value))
        it.printf(col3 + gap, base_y, id(normal_font), "%3.0f%%", perc);

      base_y += rowgap;

      it.print(col1 + gap, base_y - halfgap, id(tiny_font), "Solar kW");
      it.print(col2 + gap, base_y - halfgap, id(tiny_font), "House kW");
      it.print(col3 + gap, base_y - halfgap, id(tiny_font), "Battery %");

      it.print(col1, base_y, id(small_icons_font), weather_icon_color, "\U000F0D9C");
      value = id(solar_energy).state / 1000.;
      if (NOT_NAN(value))
        it.printf(col1 + gap, base_y, id(normal_font), "%.2f", value);

      it.print(col2, base_y, id(small_icons_font), weather_icon_color, "\U000F1904");
      value = id(load_energy).state / 1000.;
      if (NOT_NAN(value))
        it.printf(col2 + gap, base_y, id(normal_font), "%.2f", value);

      it.print(col3, base_y, id(small_icons_font), weather_icon_color, "\U000F12A5");
      value = id(battery_level).state;
      if (NOT_NAN(value))
        it.printf(col3 + gap, base_y, id(normal_font), "%3.0f", value);

      // base_y += rowgap;

      // it.print(col2, base_y, id(small_icons_font), weather_icon_color, "\U000F1901");
      // value = id(battery_power).state / 1000.;
      // if (NOT_NAN(value))
      //   it.printf(col2 + gap, base_y, id(normal_font), "%.2f kW", value);
      // else
      //   it.print(col2 + gap, base_y, id(normal_font), "---");

      // base_y += 50;
      // conditions = id(ems_mode).state;
      // if (strncmp(conditions.c_str(), "Self", 4) == 0)
      //   conditions = "Normal";
      // else {
      //   conditions = id(battery_mode).state;
      //   if (strncmp(conditions.c_str(), "Stop", 4) == 0)
      //     conditions = "Battery Off";
      // }
      // it.print(col2 + gap, base_y, id(tiny_font), weather_icon_color, conditions.c_str());


color:
  - id: weather_icon_color
    red: 100%
    blue: 100%
    green: 100%


switch:
  - platform: restart
    id: restart_switch
    name: ${device_name} Restart

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Australia/Canberra

sensor:
  - platform: homeassistant
    name: Load Energy
    id: load_energy
    entity_id: sensor.load_power

  - platform: homeassistant
    name: Solar Energy
    id: solar_energy
    entity_id: sensor.total_dc_power

  - platform: homeassistant
    name: battery_level
    id: battery_level
    entity_id: sensor.battery_level

  - platform: homeassistant
    name: battery_power
    id: battery_power
    entity_id: sensor.signed_battery_power

  - platform: homeassistant
    name: Outdoor temperature
    id: outdoor_temperature
    entity_id: sensor.bromellws_sensors_temperature
  - platform: homeassistant
    name: rain_today
    id: rain_today
    entity_id: sensor.bromellws_sensors_precipitation_today
  - platform: homeassistant
    name: rain_rate
    id: rain_rate
    entity_id: sensor.bromellws_sensors_precipitation_rate

  - platform: homeassistant
    name: Humidity
    id: humidity
    entity_id: sensor.bromellws_sensors_humidity
    
  - platform: homeassistant
    name: tank_level
    id: tank_level
    entity_id: sensor.sprinklers_tanklevel
  - platform: homeassistant
    name: Kitchen Temp
    id: kitchen_temp
    entity_id: sensor.kitchen_temp
  - platform: homeassistant
    name: Kitchen Humidity
    id: kitchen_humidity
    entity_id: sensor.kitchen_humidity
  - platform: homeassistant
    name: Bedroom Temp
    id: bedroom_temp
    entity_id: sensor.bedroom_temp
  - platform: homeassistant
    name: Lounge Temp
    id: lounge_temp
    entity_id: sensor.lounge_temp
  - platform: homeassistant
    name: House Temp
    id: house_temp
    entity_id: sensor.house_temp
  - platform: homeassistant
    name: Max Temp
    id: max_temp
    entity_id: sensor.wanniassa_temp_max_0
  - platform: homeassistant
    name: Min Temp
    id: min_temp
    entity_id: sensor.wanniassa_temp_min_0
  - platform: homeassistant
    name: Feels Like Temp
    id: feels_temp
    entity_id: sensor.tuggeranong_temp_feels_like
  - platform: homeassistant
    name: Max Rain
    id: max_rain
    entity_id: sensor.wanniassa_rain_amount_max_0
  - platform: homeassistant
    name: min Rain
    id: min_rain
    entity_id: sensor.wanniassa_rain_amount_min_0
  - platform: homeassistant
    name: Rain Change
    id: rain_chance
    entity_id: sensor.wanniassa_rain_chance_0

text_sensor:
  - platform: homeassistant
    name: ems_mode
    id: ems_mode
    entity_id: sensor.ems_mode_selection

  - platform: homeassistant
    name: battery_mode
    id: battery_mode
    entity_id: sensor.battery_forced_charge_discharge_cmd

  - platform: homeassistant
    name: Weather Description
    id: weather_desc
    entity_id: sensor.wanniassa_extended_text_0
  - platform: homeassistant
    name: Weather Word
    id: weather_word
    entity_id: sensor.wanniassa_icon_descriptor_0
  - platform: homeassistant
    name: Weather Icon
    id: weather_icon
    entity_id: sensor.wanniassa_mdi_icon_0

interval:
  - interval: 300s
    then:
      - component.update: epaper_display



