esphome:
  name: reargate
  friendly_name: reargate

esp32:
  board: esp32dev
  framework:
    type: esp-idf


i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  #frequency: 10kHz

sensor:
  - platform: ina226
    id: power_sensor
    address: 0x40
    shunt_resistance: 0.1 ohm
    max_current: 5A
    adc_time: 1100us
    adc_averaging: 64
    power:
      name: "Power"
      id: gate_power
      on_value_range:
        - above: 8
          then:
            if:
              condition: 
                - lambda: 'return id(gate).position < 0.8;'
              then:
                - cover.toggle: gate
                - cover.toggle: gate
                - delay: 2 sec
                - cover.stop: gate

# LED exposed as binary light
output:
  - platform: gpio
    pin: GPIO23
    id: output_led

light:
  - platform: binary
    id: light_led
    name: LED
    internal: true
    output: output_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: button
    internal: true
    filters:
      - delayed_on: 100ms
    on_press:
      then:
        - cover.toggle: gate
    on_click:
    - min_length: 1s
      max_length: 5s
      then:
        - switch.toggle: hold

# Relays exposed as switches
switch:
  - platform: gpio
    pin: GPIO16
    id: relay_1
    name: Close Relay
    internal: true
    interlock: [relay_2]
    on_turn_on:
    # - light.turn_on: light_led
    - delay: 12s
    - switch.turn_off: relay_1
    # - light.turn_off: light_led

  - platform: gpio
    pin: GPIO17
    id: relay_2
    name: Open Relay
    internal: true
    interlock: [relay_1]
    on_turn_on:
    # - light.turn_on: light_led
    - delay: 12s
    - switch.turn_off: relay_2
    # - script.execute: auto_close
    # - script.execute: max_open_timer

  - platform: template
    id: hold
    name: Hold Open
    optimistic: true
    assumed_state: false
    on_turn_on:
    - cover.stop: gate
    - delay: 1s
    - cover.open: gate
    on_turn_off:
    - delay: 1s
    - cover.close: gate

cover:
  - platform: time_based
    id: gate
    name: Gate
    manual_control: true
    has_built_in_endstop: true
    open_action:
      - switch.turn_on: relay_2
      - script.execute: auto_close
      - script.execute: max_open_timer
    open_duration: 10s
    close_action:
      - script.stop: auto_close
      - light.turn_off: light_led
      - switch.turn_on: relay_1
      - switch.turn_off: hold
    close_duration: 10s

    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
      - delay: 500ms
      - component.update: power_sensor

number:
  - platform: template
    id: open_duration
    name: Open Duration (Seconds)
    optimistic: true
    initial_value: 90
    min_value: 5
    max_value: 1200
    step: 5

  - platform: template
    id: hold_duration
    name: Hold Duration (Mins)
    optimistic: true
    initial_value: 90
    min_value: 5
    max_value: 360
    step: 1

script:
  - id: auto_close
    mode: restart
    then:
      - light.turn_off: light_led
      - if:
          condition:
            - switch.is_off: hold
          then:
          - light.turn_on: light_led
          - delay: !lambda 'return id(open_duration).state * 1000;' 
          - cover.close: gate
          - light.turn_off: light_led

  - id: max_open_timer
    mode: restart
    then:
      - delay: !lambda 'return id(hold_duration).state * 60 * 1000;' 
      - cover.close: gate

interval:
  - interval: 250ms
    then:
      - if:
          condition:
            lambda: 'return id(gate).current_operation != CoverOperation::COVER_OPERATION_IDLE;'
          then:
            - component.update: power_sensor

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "U4RGsTGSQMh+mjaPjQuRHSIBk+h/de2FAJ3kRtXN+mk="

ota:
  - platform: esphome
    password: "ee535e173be93995552584f648726373"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Reargate Fallback Hotspot"
    password: "dAG2sj2h34SH"

captive_portal:

web_server:
